user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_usuario_index:
    path: /user/index
    defaults: { _controller: UserBundle:Usuario:index}
    
user_usuario_add:
    path: /user/add
    defaults: { _controller: UserBundle:Usuario:add}
    
user_usuario_edit:
    path: /user/edit/{id}
    defaults: { _controller: UserBundle:Usuario:edit}
    
user_usuario_view:
    path: /user/view/{id}
    defaults: { _controller: UserBundle:Usuario:view}
    
user_usuario_delete:
    path: /user/delete/{id}
    defaults: { _controller: UserBundle:Usuario:delete}
